secrets:
  gcp_sa:
    file: ./secrets/gcp-sa.json

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agent-api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/tmp/kraft-combined-logs

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:19092
    depends_on:
      - kafka

  backend:
    build:
      context: .
      dockerfile: backend/Apps/AgentSupport/AgentSupport.Api/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

      # Postgres
      - PostgresOptions__ConnectionString=Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=agent-api;Include Error Detail=true
      - PostgresOptions__AutoMigration=false

      # MinIO
      - MinioOptions__Endpoint=minio:9000
      - MinioOptions__AccessKey=minio
      - MinioOptions__SecretKey=minio123
      - MinioOptions__BucketName=stickers
      - MinioOptions__UseSsl=false

      # Kafka
      - KafkaOptions__BootstrapServers=kafka:19092
      - KafkaOptions__RpcTimeoutSeconds=30
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      kafka:
        condition: service_started

  # Одноразовый контейнер для создания записей чтобы тестить
  db_seed:
    image: postgres:16-alpine
    container_name: db_init
    restart: "no"
    profiles: [ "tools" ]
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./seeds:/seeds:ro
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "psql -h postgres -U postgres -d agent-api -v ON_ERROR_STOP=1 -f /seeds/init.sql"

  # Одноразовый контейнер чтобы удалить все записи
  db_cleanup_all:
    image: postgres:16-alpine
    container_name: db_all_clean
    restart: "no"
    profiles: [ "tools" ]
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./seeds:/seeds:ro
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "psql -h postgres -U postgres -d agent-api -v ON_ERROR_STOP=1 -f /seeds/clean_all.sql"

  # Одноразовый контейнер чтобы удалить 1 запись
  db_clean:
    image: postgres:16-alpine
    container_name: db_clean
    restart: "no"
    profiles: [ "tools" ]
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./seeds:/seeds:ro
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "psql -h postgres -U postgres -d agent-api -v ON_ERROR_STOP=1 -f /seeds/clean.sql"

  # Авторизация и аутентификация Payk96
  keycloak_1:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloakSQL
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_SPI_CORS_ALLOWED_ORIGINS=*
      - KC_SPI_CORS_ENABLED=true
    ports:
      - "8484:8080"
    command: start-dev
    depends_on:
      - keycloakSQL
    restart: unless-stopped

  keycloakSQL:
    container_name: keycloakSQL
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak
    ports:
      - "5433:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    restart: unless-stopped

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: ml
    restart: unless-stopped
    ports:
      - "6767:6767"
    environment:
      - RUBERT_MODEL=cointegrated/rubert-tiny2

  smtp_connector:
    build:
      context: .
      dockerfile: backend/Apps/SmtpConnector/Api/Dockerfile
    secrets:
      - gcp_sa
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
      # Postgres
      - PostgresOptions__ConnectionString=Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=agent-api;Include Error Detail=true
      - PostgresOptions__AutoMigration=true
  
      # Kafka (для контейнеров правильнее kafka:19092)
      - KafkaOptions__BootstrapServers=kafka:19092
      - KafkaOptions__RpcTimeoutSeconds=30
  
      # PubSub
      - PubSubOptions__ProjectId=glass-sylph-488810-k2
      - PubSubOptions__SubscriptionId=gmail-inbox-sub
      - PubSubOptions__ServiceAccountJsonPath=/run/secrets/gcp_sa
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_sa
      - GOOGLE_CLOUD_PROJECT=glass-sylph-488810-k2
        
      # Gmail
      - GmailOptions__ApplicationName=SmtpConnector
      - GmailOptions__UserId=me
      - GmailOptions__ClientId=${GMAIL_CLIENT_ID}
      - GmailOptions__ClientSecret=${GMAIL_CLIENT_SECRET}
      - GmailOptions__RefreshToken=${GMAIL_REFRESH_TOKEN}
      - GmailOptions__TopicName=projects/glass-sylph-488810-k2/topics/smtp
      - GmailOptions__LabelIds__0=INBOX


  telegram_bot:
    build: bot/
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=8657445324:AAHYZLDx7jz-rQAHVjxuZalnikQz2qrm6t0
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=notifications
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=agent-api
      - TZ=Europe/Moscow
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

volumes:
  postgres_data:
  minio_data:
  kafka_data:
  keycloak_data:
